### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by gabrielgou** [gabrielgou/RobotsGabriel-Jorge#1]
Professor, 
quando dois robôs se chocam formará um lixo, o qual se outro robô for pra cima também será destruído.
A questão é, se o humano for pra cima do lixo, o que acontece com ele?
Ele morre, Não acontece nada, ou ele é barrado de ir pra cima do lixo?

**Comment by gabrielgou** [comment]
Outra é, eu posso fazer minhas próprias regras de jogo?
ex: o jogador só pode fazer um teleporte seguro por level ou uma vaporização
minha tabela ser 16x16?

**Comment by drbeco** [comment]
Você não pode criar regras, deve programar de acordo com o que foi especificado. Isso é meio óbvio, não é? Isso é um exercício.

Sobre as regras, recomendo você jogar o original. Basta chamar `robots` no servidor.

**Comment by drbeco** [comment]
Não crie **bugs** iniciando com **professor** e título **dúvida**.

Bugs são para relatar problemas para seu parceiro, específico. E se eu entrar na conversa para ajudar, sorte (ou azar, depende) a vossa.
