### ISSUE TITLE
system

### ISSUE THREAD

**Issue by drbeco** [gabrielgou/RobotsGabriel-Jorge#2]
"System" chama o sistema operacional para executar um comando externo de outra linguagem (que varia de acordo com o sistema operacional!)

Você está restrito a executar comandos da linguagem C, e não de outras linguagens.

Resolva o que tem que ser resolvido programando apenas em C.

Além do que, envolve questões de segurança já explicadas em sala.

**Comment by gabrielgou** [comment]
Okay professor, vi que o o comando "printf("\e[H\e[2J");" resolveu meu problema.
obrigado.
