### ISSUE TITLE
Teste

### ISSUE THREAD

**Issue by gabrielgou** [gabrielgou/RobotsGabriel-Jorge#3]
Verificar possíveis Bugs do programa.

**Comment by drbeco** [comment]
Boa tarde.

Esse issue está MUITO vago. Cada issue deve se referir a um **bug específico** com sua descrição, com as tentativas de solução na discussão, e quando resolvido, discutir a solução e fechar.

Entendido?

**Comment by JorgeEd13** [comment]
Programa testado, nenhum bug encontrado.
